[book]
title = "NextFTC Documentation"
language = "en"
multilingual = false
src = "src"

[preprocessor.tabs]

[output.html]
additional-css = ["theme/tabs.css"]
additional-js = ["theme/tabs.js"]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/rowan-mcalpin/NextFTC-Docs"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/rowan-mcalpin/NextFTC-Docs/issues"